# -*- coding: utf-8 -*-
"""růst řas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ABd0_J7F_bCuA6YOCk-r1btjZPX2LxnV
"""

a = 'A'
b = 'B'
ab = ['A', 'B']
rada = [a]

pravidla = {a: ab,
            b: a}

opakovani = int (input('počet generací: '))

def lsystem (rada, pravidla, opakovani):
  for _ in range (opakovani):
    x = []
    for pismenko in rada:
      if pismenko in pravidla:
        x += pravidla[pismenko]
    rada = x
  return rada

for q in range (opakovani+1):
  print('generace {}: {}'.format(q, lsystem(rada,pravidla, q)))

